Repository Rebels-Y3S2/Automobile-spare-parts-frontend, pull requests merged in 2022-08, with the labels that each got.

#10 Feature/reservations
  .env
  package-lock.json
  src/App.js
  src/api/Item/item.request.js
  src/api/Order/order.request.js
  src/api/apiInstance.js
  src/components/PreviewPage/PreviewFooter.jsx
  src/components/Profile/ProfileSideNav.jsx
  src/pages/items/index.jsx
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
  src/pages/reservations/reservation.module.css
Labels: feature

#16 Feature/reservations
  package-lock.json
  package.json
  public/images/trash.svg
  src/api/Order/order.request.js
  src/components/Accordion/AccordionLayout.jsx
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
Labels: enhancement, feature

#20 Feature/reservations
  package-lock.json
  src/components/Accordion/AccordionLayout.jsx
  src/pages/items/index.jsx
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
Labels: enhancement, bug fixed

#22 Fixed the issue with the env file variables
  .env
  package-lock.json
  package.json
  src/api/apiInstance.js
  webpack.config.js
Labels: bug fixed

#25 Modified UIs in My Reservations and Reserve Now
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
Labels: enhancement

#36 Feature/reservations
  src/api/Order/order.request.js
  src/components/Accordion/AccordionLayout.jsx
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
Labels: enhancement, feature, bug fixed

#37 Delete reservation details interface implemented
  src/api/Order/order.request.js
  src/pages/reservations/MyReservations.jsx
Labels: feature

#42 User management related fixing + Edit profile implementation
  src/components/Profile/EditProfile.jsx
  src/components/dialog/Dialog.jsx
  src/pages/login/index.jsx
  src/pages/login/styles.module.css
  src/pages/profile/index.jsx
  src/pages/signup/index.jsx
Labels: enhancement, feature, bug fixed

#50 Preview, signup, loader and style changes
  public/images/carousel1.jpg
  public/images/carousel122.jpg
  public/images/carousel2.jpg
  public/images/carousel21.jpg
  public/images/carousel3.jpg
  public/images/carousel333.jpg
  src/components/LayoutComponents/Loader.jsx
  src/components/LayoutComponents/index.css
  src/components/PreviewPage/Carousel.jsx
  src/components/PreviewPage/PreviewHeader.jsx
  src/components/PreviewPage/ServiceCards.jsx
  src/pages/login/index.jsx
  src/pages/preview-page/index.jsx
  src/pages/signup/index.jsx
Labels: feature, bug fixed
