Repository Rebels-Y3S2/Automobile-spare-parts-frontend, pull requests merged in 2022-09, with the labels that each got.

#54 Prod and Dev URL Switch issue fixed
  .env
  package.json
Labels: bug fixed

#57 Feature/reservations
  src/App.js
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/ReserveNow.jsx
  src/pages/reservations/index.jsx
  src/pages/reservations/reservation.module.css
Labels: enhancement, bug fixed

#59 ENV issue in prod site fixed
  package.json
  src/api/apiInstance.js
Labels: bug fixed

#65 Feature/reservations
  src/components/DialogComponent/DialogSM.jsx
  src/components/DialogComponent/DialogXL.jsx
  src/components/LayoutComponents/NavBar.jsx
  src/pages/reservations/DeleteReservation.jsx
  src/pages/reservations/MyReservations.jsx
  src/pages/reservations/UpdateReservation.jsx
Labels: enhancement, bug fixed

#76 Integrated reservationRequests function to Frontend
  package.json
  src/App.js
  src/api/Order/order.request.js
  src/components/DialogComponent/Dialog.jsx
  src/components/DialogComponent/DialogXL.jsx
  src/components/Table/Table.jsx
  src/pages/reservations/DeleteReservation.jsx
  src/pages/reservations/ReservationRequests.jsx
  src/pages/reservations/ReserveNow.jsx
  src/pages/reservations/UpdateReservation.jsx
Labels: enhancement, feature

#79 View all users, update, delete functions - Admin
  src/App.js
  src/api/User/userApi.js
  src/components/ManageAdminPanel/DeleteUser.jsx
  src/pages/admin-panel/index.jsx
  src/pages/admin-panel/view-users.jsx
Labels: enhancement, feature, bug fixed

#87 Updated react charts version and created the base of order report
  package.json
  src/App.js
  src/api/Order/order.request.js
  src/components/report/charts/DoughnutChart.jsx
  src/pages/reservations/OrderReport.jsx
  src/pages/reservations/QuestionReport.css
Labels: enhancement, feature

#91 Feature/reservation requests
  src/components/Table/Table.jsx
  src/components/report/header/ReportHeader.jsx
  src/pages/reservations/OrderReport.jsx
  src/pages/reservations/QuestionReport.css
Labels: enhancement

#92 added the order report path to admin panel
  src/pages/admin-panel/index.jsx
  src/pages/reservations/OrderReport.jsx
Labels: enhancement

#93 Users report functionality
  src/components/ManageAdminPanel/DeleteUser.jsx
  src/pages/admin-panel/index.jsx
  src/pages/users-report/UsersReport.jsx
Labels: enhancement, feature
